version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/config/redis.config
    command: ["redis-server", "/config/redis.config"]
